quality: 20
ouput_dir: C:\ToT\Proxies
input_base_dir: D:\Backups
directories:
  2019 Mi 9T\Camera:
    filename_patterns:
      - "VID*2019*.mp4"
      - "VID*2020*.mp4"
  "2020 Insta360 One R":
    filename_patterns:
      - "*.mp4"
